project:
  type: website
  output-dir: docs

website:
  title: "Mac Graveur"
  navbar:
    left:
      - href: index.qmd
        text: Accueil
        icon: bi-house-door-fill
      - href: veille/index.qmd
        icon: bi-bookmark
        text: Veille
      - href: about.qmd
        icon: bi-person-bounding-box
        text: Qui suis-je ?
      - href: realisation.qmd
        text: Réalisations
        icon: bi-bricks
      - href: publication.qmd
        text: Publications
        icon: bi-pen-fill
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



