project:
  type: website
  output-dir: docs

website:
  title: "Testpages_1"
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - href: veille/index.qmd
        icon: bi-binoculars
        text: Veille
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



