---
title: Publications
---

* Faire des archives des communs. In _La Gazette des archives_, n°271, 2024. Archives en communs : commun, _open data_ et archive ?. pp. 75-90.

* Archives et communautés à la lumière des communs, in Document et archivage : pratiques formelles et informelles dans les organisations Actes du 23eme colloque international sur le document numérique (CiDE.23), 2024.

* La salle de lecture, hors du temps et de l’espace ?. In: _La Gazette des archives_, n°253, 2019-1. Le goût de l’archive à l’ère numérique. pp. 17-27. <https://doi.org/10.3406/gazar.2019.5683>

* Avec Maud Jouve-Profizi. L’archiviste, médiateur de la donnée ?. In: _La Gazette des archives_, n°251, 2018-3. L'archiviste-caméléon, médiateur du quotidien. pp. 153-166. <https://doi.org/10.3406/gazar.2018.5639>

* L’archiviste au coeur de l’institution. In: _La Gazette des archives_, n°244, 2016-4. Les mutations du métier d'archiviste et de son environnement. Actes du 11e colloque national des archivistes communaux et intercommunaux 2-4 juin 2015 (Limoges) pp. 155-168. <https://doi.org/10.3406/gazar.2016.5417>